# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b9d7cff90496931f75fe2b63c6fedbfde96784aab886d44062fcc7f2e603465f0c53e2e8c8cb98f1611bef7611687a207d4383329ca2c04c93082b4479ec7c7

test:
  secret_key_base: 2fb915783d85501181a5348ac5d61ac6c77acfac6d8e46142af9c753b9ce264bce75aeb092f0abc1cdf8b99de2c87c630761057ee8c5a85149ee1c9bda92420f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
